[package]
name = "esp32s3_box_graphics_tester"
version = "0.1.0"
authors = ["Samuel Benko <samuel.benko@espressif.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-graphics = "0.8.1"
embedded-graphics-simulator = "0.5.0"
embedded-graphics-framebuf = "0.5.0"
